#nullable disable
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

//Generated by ScaffoldApp.
namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TagsController : Controller
    {
        // Add service injections here
        private readonly ITagService _tagService;

        public TagsController(ITagService tagService)
        {
            _tagService = tagService;
        }

        [AllowAnonymous]
        public IActionResult Index(bool? isDeleteSuccesful = null)
        {
            if(isDeleteSuccesful == true)
            {
                ViewBag.DeleteMessage = "Tag deleted successfully.";
            }
            List<TagModel> tagList = _tagService.GetList(); // TODO: Add get list service logic here
            return View(tagList);
        }

        // GET: Tags/Details/5
        public IActionResult Details(int id)
        {
            TagModel tag = _tagService.GetItem(id); // TODO: Add get item service logic here
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TagModel tag)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add insert service logic here
                var result = _tagService.Add(tag);
                if(result.IsSuccessful)
                    return RedirectToAction("Index");
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(tag);
        }

        // GET: Tags/Edit/5
        public IActionResult Edit(int id)
        {
            TagModel tag = _tagService.Query().SingleOrDefault(t => t.Id == id); // TODO: Add get item service logic here
            if (tag == null)
            {
                return NotFound();
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(tag);
        }

        // POST: Tags/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TagModel tag)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                var result = _tagService.Update(tag);
                if(result.IsSuccessful)
                    return RedirectToAction("Index");
                ModelState.AddModelError("", result.Message);
            }
            // Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            return View(tag);
        }

        // GET: Tags/Delete/5
        public IActionResult Delete(int id)
        {
            TagModel tag = _tagService.GetItem(id); // TODO: Add get item service logic here
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            var result = _tagService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
	}
}
